// ═══════════════════════════════════════════════════
//  SILKBOUND PRO — World / Room Data
//  FIX: Single-pass ROOM_MAP build (was double-writing,
//       leaving stale reference before pixelW/H set)
// ═══════════════════════════════════════════════════
import { TILE } from '../constants.js';

export const ROOMS = [
  // ══ FORGOTTEN DEPTHS ════════════════════════════
  {
    id:'depths_start', biome:'depths', rx:0, ry:0,
    area:'FORGOTTEN DEPTHS',
    tiles:[
      '................................',
      '................................',
      '................................',
      '.....#####......................',
      '................................',
      '..........######................',
      '................................',
      '.####.....................####..',
      '................................',
      '..............######............',
      '...#####........................',
      '................................',
      '....................######......',
      '................................',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'crawler',tx:16,ty:13},
      {type:'crawler',tx:24,ty:9},
    ],
    collectibles:[
      {type:'geo', tx:12,ty:9,  val:5},
      {type:'geo', tx:5, ty:7,  val:3},
      {type:'shard',tx:15,ty:3},
    ],
    npcs:[{
      tx:3,ty:13, id:'elder', name:'Elder Moth',
      questId:'main_1',
      lines:[
        '...You awaken at last, vessel.',
        'The kingdom weeps in darkness.',
        'Three ancient Shards must be reunited.',
        'Seek the Crystal Heart to the east.',
        'Then ascend to the Sky Temple.',
        'I will await your return here.',
      ],
    }],
    exits:[{tx:31,ty:13,dir:'right',to:'depths_mid'}],
    spawnTx:2, spawnTy:13,
    loot:{tx:27,ty:6, ability:'wallslide', name:'WALL SLIDE', desc:'Cling to walls and slow your descent.'},
    secret: false,
  },
  {
    id:'depths_mid', biome:'depths', rx:1, ry:0,
    area:'FORGOTTEN DEPTHS',
    tiles:[
      '................................',
      '................................',
      '..............#..##.............',
      '................................',
      '.......######.................#.',
      '................................',
      '.###..........................#.',
      '................................',
      '............#####.............#.',
      '..#####....................####.',
      '................................',
      '..........ppppppp...............',
      '...##...........................',
      '...##...........................',
      '...##....####......#####...####.',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'crawler',  tx:14,ty:14},
      {type:'flyer',    tx:22,ty:5},
      {type:'ranged',   tx:18,ty:8},
      {type:'tank',     tx:26,ty:14},
    ],
    collectibles:[
      {type:'geo',   tx:20,ty:4,  val:8},
      {type:'geo',   tx:27,ty:4,  val:4},
      {type:'health',tx:5, ty:5},
      {type:'geo',   tx:10,ty:11, val:6},
    ],
    npcs:[{
      tx:3,ty:13, id:'merchant_depths', name:'Pale Merchant',
      isMerchant:true,
      lines:['My wares are yours, for a price.'],
    }],
    exits:[
      {tx:0,  ty:13, dir:'left', to:'depths_start'},
      {tx:31, ty:13, dir:'right',to:'fungal_entry'},
      {tx:15, ty:0,  dir:'up',   to:'crystal_entry'},
    ],
    spawnTx:1, spawnTy:13,
    loot:{tx:26,ty:3, ability:'doublejump', name:'DOUBLE JUMP', desc:'A second leap — defy gravity itself.'},
    boss:{type:'Warden', tx:24,ty:13},
    secret: false,
  },

  // ══ SECRET ROOM (depths) ═════════════════════════
  {
    id:'depths_secret', biome:'secret', rx:0, ry:-1,
    area:'? FORGOTTEN PASSAGE ?',
    tiles:[
      '################################',
      '#..............................#',
      '#..............................#',
      '#..........#####...............#',
      '#..............................#',
      '#.....ppppppppppp..............#',
      '#...............................',
      '#...............................',
      '#....####.................####.#',
      '#..............................#',
      '#..............................#',
      '#..............................#',
      '#..............................#',
      '#.............................##',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'elite',tx:16,ty:13},
    ],
    collectibles:[
      {type:'shard',tx:16,ty:3},
      {type:'geo',  tx:8, ty:8,  val:25},
      {type:'geo',  tx:24,ty:8,  val:25},
    ],
    npcs:[],
    exits:[{tx:31,ty:7,dir:'right',to:'depths_start'}],
    spawnTx:2, spawnTy:12,
    secret: true,
    isSecret:true,
  },

  // ══ FUNGAL WASTES ════════════════════════════════
  {
    id:'fungal_entry', biome:'fungal', rx:2, ry:0,
    area:'FUNGAL WASTES',
    tiles:[
      '................................',
      '................................',
      '.......#####.......#####........',
      '................................',
      '...##...................##......',
      '................................',
      '.................#####..........',
      '.####...................#####...',
      '................................',
      '....ppppp.......ppppppp.........',
      '................................',
      '................................',
      '................................',
      '................................',
      '#....######........######.....#.',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'mushroom',tx:10,ty:14},
      {type:'mushroom',tx:20,ty:14},
      {type:'flyer',   tx:15,ty:6},
      {type:'ranged',  tx:25,ty:13},
      {type:'spike_ball', tx:8, ty:10},
      {type:'shadow_sprite', tx:22, ty:8},
      {type:'slime',   tx:16, ty:14},
    ],
    collectibles:[
      {type:'geo',   tx:7, ty:8,  val:12},
      {type:'geo',   tx:24,ty:2,  val:6},
      {type:'shard', tx:15,ty:9},
    ],
    npcs:[{
      tx:3,ty:14, id:'fungal_sage', name:'Fungal Sage',
      questId:'side_1',
      lines:[
        'Spores carry the memory of the dead.',
        'The Crystal Caverns lie above — beware.',
        'Help me collect geo, and I shall reward you.',
        'Ten geo pieces, traveller. Can you manage?',
      ],
    }],
    exits:[
      {tx:0,  ty:13,dir:'left', to:'depths_mid'},
      {tx:31, ty:13,dir:'right',to:'fungal_deep'},
    ],
    spawnTx:1, spawnTy:13,
    secret: false,
  },
  {
    id:'fungal_deep', biome:'fungal', rx:3, ry:0,
    area:'FUNGAL WASTES — DEEP',
    tiles:[
      '................................',
      '..........#####.................',
      '................................',
      '.....##.................#####...',
      '................................',
      '...........ppppp................',
      '.###............................',
      '................................',
      '.............#####..............',
      '....#####....................###',
      '................................',
      '..ppppp.......pppppppp..........',
      '................................',
      '................................',
      '.....######.......######........',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'mushroom',    tx:18,ty:14},
      {type:'crawler',     tx:8, ty:8},
      {type:'flyer',       tx:25,ty:4},
      {type:'mushroom',    tx:14,ty:8},
      {type:'elite',       tx:20,ty:13},
      {type:'necromancer', tx:12, ty:10},
      {type:'ghost',       tx:28, ty:6},
      {type:'spike_ball',  tx:5, ty:12},
    ],
    collectibles:[
      {type:'geo',   tx:6, ty:6,  val:15},
      {type:'health',tx:22,ty:3},
      {type:'shard', tx:16,ty:5},
    ],
    npcs:[],
    exits:[
      {tx:0,  ty:13,dir:'left',to:'fungal_entry'},
      {tx:15, ty:0, dir:'up',  to:'crystal_caverns'},
    ],
    spawnTx:2, spawnTy:13,
    loot:{tx:14,ty:4, ability:'dash', name:'SHADOW DASH', desc:'A burst of speed — become shadow itself.'},
    secret: false,
  },

  // ══ CRYSTAL CAVERNS ══════════════════════════════
  {
    id:'crystal_entry', biome:'crystal', rx:1, ry:-1,
    area:'CRYSTAL CAVERNS',
    tiles:[
      '................................',
      '................................',
      '.......#####.......#####........',
      '................................',
      '..##.......................##...',
      '................................',
      '.................#####..........',
      '.####...........................',
      '................................',
      '....#####......####.............',
      '................................',
      '................................',
      '.....##...................##....',
      '................................',
      '....######.......######.........',
      '###############pp###############',
      '###############..###############',
      '###############..###############',
      '###############..###############',
      '###############..###############',
    ],
    enemies:[
      {type:'crystal_wyrm',tx:20,ty:14},
      {type:'crystal_wyrm',tx:8, ty:9},
      {type:'flyer',       tx:15,ty:4},
      {type:'sentinel',    tx:26,ty:13},
    ],
    collectibles:[
      {type:'geo',   tx:5, ty:3,  val:18},
      {type:'geo',   tx:25,ty:6,  val:10},
      {type:'shard', tx:12,ty:2},
    ],
    npcs:[{
      tx:28,ty:13, id:'seer', name:'Crystal Seer',
      lines:[
        'The light refracts... I see your path.',
        'Two seals remain — the Temple and the Void.',
        'Collect the Shards. They unlock the final gate.',
        'The Void King cannot be reasoned with.',
        'Only strength of nail can mend what is broken.',
      ],
    }],
    exits:[
      {tx:15,ty:19,dir:'down',to:'depths_mid'},
      {tx:31,ty:13,dir:'right',to:'crystal_caverns'},
    ],
    spawnTx:2, spawnTy:13,
    secret: false,
  },
  {
    id:'crystal_caverns', biome:'crystal', rx:2, ry:-1,
    area:'CRYSTAL CAVERNS — HEART',
    tiles:[
      '................................',
      '..........#####.................',
      '................................',
      '...##...................##......',
      '................................',
      '............#####...............',
      '.###............................',
      '................................',
      '.........ppppp.......ppppp......',
      '....#####....................###',
      '................................',
      '................................',
      '.....##...................##....',
      '................................',
      '...######.........######........',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'crystal_wyrm',tx:10,ty:14},
      {type:'crystal_wyrm',tx:22,ty:14},
      {type:'flyer',       tx:16,ty:5},
      {type:'crystal_wyrm',tx:6, ty:8},
      {type:'sentinel',    tx:18,ty:13},
    ],
    collectibles:[
      {type:'geo',   tx:14,ty:8,  val:20},
      {type:'geo',   tx:24,ty:2,  val:12},
      {type:'health',tx:4, ty:5},
    ],
    npcs:[{
      tx:2,ty:13, id:'merchant_crystal', name:'Lost Trader',
      isMerchant:true,
      lines:['Strange place to set up shop, I know.','But business must go on.'],
    }],
    exits:[
      {tx:0,  ty:13,dir:'left',to:'crystal_entry'},
      {tx:15, ty:0, dir:'up',  to:'temple_entry'},
    ],
    spawnTx:1, spawnTy:13,
    boss:{type:'CrystalGuardian', tx:22,ty:13},
    loot:{tx:20,ty:3, ability:'nail2', name:'NAIL MASTERY', desc:'Sharpen your strike — pierce armored foes.'},
    secret: false,
  },

  // ══ SKY TEMPLE ═══════════════════════════════════
  {
    id:'temple_entry', biome:'temple', rx:2, ry:-2,
    area:'SKY TEMPLE',
    tiles:[
      '................................',
      '................................',
      '..........#####.................',
      '................................',
      '....##.................##.......',
      '................................',
      '.................#####..........',
      '.####...........................',
      '................................',
      '....##.........######...........',
      '................................',
      '...ppppp.......ppppppp..........',
      '................................',
      '................................',
      '....#####.........#####.........',
      '###############pp###############',
      '###############..###############',
      '###############..###############',
      '###############..###############',
      '###############..###############',
    ],
    enemies:[
      {type:'sentinel',tx:12,ty:14},
      {type:'sentinel',tx:22,ty:14},
      {type:'flyer',   tx:16,ty:4},
      {type:'elite',   tx:18,ty:13},
    ],
    collectibles:[
      {type:'geo',   tx:8, ty:9,  val:25},
      {type:'geo',   tx:24,ty:6,  val:15},
      {type:'shard', tx:15,ty:3},
    ],
    npcs:[{
      tx:3,ty:13, id:'ascendant', name:'Ascendant Spirit',
      lines:[
        'You have climbed far, vessel.',
        'The Void King awaits at the pinnacle.',
        'Three Shards unlock the final seal.',
        'Face him — and mend what was broken.',
      ],
    }],
    exits:[
      {tx:15,ty:19,dir:'down', to:'crystal_caverns'},
      {tx:31,ty:7, dir:'right',to:'temple_peak'},
    ],
    spawnTx:2, spawnTy:13,
    secret: false,
  },
  {
    id:'temple_peak', biome:'temple', rx:3, ry:-2,
    area:'SKY TEMPLE — PINNACLE',
    tiles:[
      '................................',
      '..........#####.................',
      '..#...........................#.',
      '..#...........................#.',
      '..#.....#####.....#####.......#.',
      '..#...........................#.',
      '..#...........................#.',
      '..####........................#.',
      '..............................#.',
      '.............#####..............',
      '................................',
      '...ppppppp.......ppppppp........',
      '................................',
      '................................',
      '....######.........######.......',
      '################################',
      '################################',
      '################################',
      '################################',
      '################################',
    ],
    enemies:[
      {type:'sentinel', tx:14,ty:14},
      {type:'sentinel', tx:20,ty:14},
      {type:'flyer',    tx:8, ty:4},
      {type:'flyer',    tx:24,ty:4},
      {type:'elite',    tx:16,ty:13},
    ],
    collectibles:[
      {type:'geo',   tx:6, ty:3,  val:30},
      {type:'health',tx:26,ty:3},
    ],
    npcs:[],
    exits:[{tx:0,ty:7,dir:'left',to:'temple_entry'}],
    spawnTx:2, spawnTy:13,
    boss:{type:'VoidKing', tx:16,ty:13},
    isFinal: true,
    secret: false,
  },
];

// ── FIXED: Single-pass map build ─────────────────────
// Previously ROOM_MAP was populated twice — first without pixelW/H,
// then again after computing it. This left a window where the map
// held a stale object missing those fields, which could cause
// camera.y = NaN and subsequently crash loadRoom() mid-transition.
export const ROOM_MAP = {};
ROOMS.forEach(r => {
  // Validate tile array integrity
  if (!r.tiles || !Array.isArray(r.tiles) || r.tiles.length === 0) {
    console.error(`[Rooms] Room "${r.id}" has no valid tiles array`);
    r.tiles = ['################################'];
  }
  const rowLen = r.tiles[0].length;
  for (let i = 1; i < r.tiles.length; i++) {
    if (r.tiles[i].length !== rowLen) {
      console.warn(`[Rooms] Room "${r.id}" row ${i} length mismatch — padding`);
      r.tiles[i] = r.tiles[i].padEnd(rowLen, '.').slice(0, rowLen);
    }
  }
  // Compute pixel dimensions BEFORE adding to map
  r.pixelW = r.tiles[0].length * TILE;
  r.pixelH = r.tiles.length    * TILE;
  ROOM_MAP[r.id] = r;
});
